### ISSUE TITLE
github action

### ISSUE THREAD

**Issue by Alice52** [lianshun1000/secondKill#1]
```yaml
name: Build sencondKill

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.events.head_commit.message,'ci skip')"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build JavaSE Tutorial
        run: mvn clean package -DskipTests=true
```
